/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iPane;

import rojerusan.RSPanelsSlider;
import Visual.MENU;
import static Visual.MENU.pnlSlider;
import static iPane.panelBebidas.panelPapas;

/**
 *
 * @author nello
 */
public class panelButtons extends javax.swing.JPanel {

    /**
     * Creates new form panelButtons
     */
    public panelButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBebidas = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnPapas = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBebidas.setBackground(new java.awt.Color(227, 223, 11));
        btnBebidas.setText("      Bebidas");
        btnBebidas.setToolTipText("");
        btnBebidas.setAutoscrolls(true);
        btnBebidas.setBackgroundHover(new java.awt.Color(227, 223, 11));
        btnBebidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KITCHEN);
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });

        btnPapas.setBackground(new java.awt.Color(227, 223, 11));
        btnPapas.setText("      Papas");
        btnPapas.setToolTipText("");
        btnPapas.setAutoscrolls(true);
        btnPapas.setBackgroundHover(new java.awt.Color(227, 223, 11));
        btnPapas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KITCHEN);
        btnPapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnPapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapasActionPerformed
if (!btnPapas.isSelected()){
            btnPapas.setSelected(true);
            btnBebidas.setSelected(false);
            
            pnlSlider.setPanelSlider(1,panelPapas, RSPanelsSlider.DIRECT.RIGHT); 
}
    }//GEN-LAST:event_btnPapasActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        if (!btnBebidas.isSelected()){
            btnPapas.setSelected(false);
            btnBebidas.setSelected(true);
            
            MENU.pnlSlider.setPanelSlider(1,panelPapas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnBebidasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnBebidas;
    private RSMaterialComponent.RSButtonMaterialIconOne btnPapas;
    // End of variables declaration//GEN-END:variables
}
